// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDWc0LvvaVBrB-yADlou9FXVqVhv1Ljg',
    appId: '1:876215292126:web:ae1c60b147a35b7534b24f',
    messagingSenderId: '876215292126',
    projectId: 'ledger-6e6c4',
    authDomain: 'ledger-6e6c4.firebaseapp.com',
    storageBucket: 'ledger-6e6c4.firebasestorage.app',
    measurementId: 'G-TDW2X6TDK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd28PAYQEcd1tk57jWRY2OgLrSf-OjGpg',
    appId: '1:876215292126:android:92c1c54a120c1d6034b24f',
    messagingSenderId: '876215292126',
    projectId: 'ledger-6e6c4',
    storageBucket: 'ledger-6e6c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZrfR8R99s5BRWKU7HQdG9OpoPVb4Sho',
    appId: '1:876215292126:ios:75e321baa3ae7f6e34b24f',
    messagingSenderId: '876215292126',
    projectId: 'ledger-6e6c4',
    storageBucket: 'ledger-6e6c4.firebasestorage.app',
    iosBundleId: 'com.example.ledgr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtZrfR8R99s5BRWKU7HQdG9OpoPVb4Sho',
    appId: '1:876215292126:ios:75e321baa3ae7f6e34b24f',
    messagingSenderId: '876215292126',
    projectId: 'ledger-6e6c4',
    storageBucket: 'ledger-6e6c4.firebasestorage.app',
    iosBundleId: 'com.example.ledgr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChDWc0LvvaVBrB-yADlou9FXVqVhv1Ljg',
    appId: '1:876215292126:web:4b86f240673b900f34b24f',
    messagingSenderId: '876215292126',
    projectId: 'ledger-6e6c4',
    authDomain: 'ledger-6e6c4.firebaseapp.com',
    storageBucket: 'ledger-6e6c4.firebasestorage.app',
    measurementId: 'G-89FDVPNGX6',
  );
}
