import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/di/providers.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/theme_provider.dart';
import 'data/services/notification_service.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire configure
import 'presentation/pages/auth/login_page.dart';
import 'presentation/pages/auth/signup_page.dart';
import 'presentation/pages/intro/intro_page.dart';
import 'presentation/pages/main_navigation_page.dart';
import 'presentation/widgets/loading_widget.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await NotificationService.init();
  runApp(
    // ProviderScope is mandatory — it's the root of the Riverpod container.
    const ProviderScope(child: ExpenseTrackerApp()),
  );
}

class ExpenseTrackerApp extends ConsumerWidget {
  const ExpenseTrackerApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);

    return MaterialApp(
      title: 'Ledgr',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeMode,
      home: const _AppRouter(),
    );
  }
}

/// Watches the global auth stream and routes to Home or Auth accordingly.
/// This is the single place that decides which screen to show — no Navigator
/// push logic needed for the initial route.
class _AppRouter extends ConsumerWidget {
  const _AppRouter();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStateProvider);

    return authState.when(
      loading: () => const Scaffold(
        body: LoadingWidget(message: 'Starting up...'),
      ),
      error: (_, __) => const _AuthFlow(),
      data: (user) => user != null ? const MainNavigationPage() : const _AuthFlow(),
    );
  }
}

/// Manages toggling between Login and Signup without Navigator.
class _AuthFlow extends StatefulWidget {
  const _AuthFlow();

  @override
  State<_AuthFlow> createState() => _AuthFlowState();
}

class _AuthFlowState extends State<_AuthFlow> {
  bool _showIntro = true;
  bool _showLogin = true;

  @override
  Widget build(BuildContext context) {
    if (_showIntro) {
      return IntroPage(
        onGetStarted: () => setState(() => _showIntro = false),
      );
    }

    return _showLogin
        ? LoginPage(
      onNavigateToSignup: () => setState(() => _showLogin = false),
    )
        : SignupPage(
      onNavigateToLogin: () => setState(() => _showLogin = true),
    );
  }
}
